name: Build and deploy

permissions:
  id-token: write
  deployments: write
  packages: write
  contents: write
  actions: read
  checks: read
  pull-requests: write
  statuses: read

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install
      - name: Run linters
        run: pnpm lint
      - name: Build for production
        run: pnpm build

      - name: Archive production artifacts 'dist'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: .output/public
          include-hidden-files: true

